

services:
  postgres:
    image: postgres
    container_name: postgres_container
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=welcome123
      - POSTGRES_USER=root
      - POSTGRES_DB=testcase
    networks:
      - mynetwork
    restart:
       unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: root@user.com
      PGADMIN_DEFAULT_PASSWORD: strong
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - mynetwork
    restart:
       unless-stopped

  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    container_name: zipkin

    environment:
      - STORAGE_TYPE=mem
      - SELF_TRACING_ENABLED=true
      - JAVA_OPTS=-Xms128m -Xmx128m -XX:+ExitOnOutOfMemoryError
    ports:
      - 9411:9411
    volumes:
      - ~/apps/postgres:/var/lib/zipkin
    networks:
      - mynetwork
    restart:
      unless-stopped



volumes:
    local_pgdata:
    pgadmin-data:


networks:
    mynetwork:
      driver: bridge


